executables:
  uv:
    pattern: "^uv.*"
    profiles:
      - base
      - online
      - uv_tools
    overrides:
      network:
        enabled: true
      filesystem:
        write:
          paths:
            - ~/.local/share/uv/

  npm:
    pattern: "^npm.*"
    profiles:
      - base
      - online
    overrides:
      network:
        enabled: true
      filesystem:
        write:
          paths:
            - ~/.local/share/npm/
            - ~/.cache/npm/

  cargo:
    pattern: "^cargo.*"
    profiles:
      - base

