[profile]
name = "julia"
description = "Julia-specific sandbox profile"

[filesystem.write]
paths = ["~/.julia", "/private/tmp/", "~/Library/Jupyter"]

[filesystem.read]
paths = ["/Applications/Julia-1.6.app", "/private/var/"]

[mach]
lookup_regex = ["^com.apple.*"]

[ipc]
allow_posix_shm = true
posix_shm_names = ["com.apple.AppleDatabaseChanged"]
allow_posix_sem = true
